# -*- coding: utf-8 -*-
"""Analysis3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1USNDhAzrfOgOsIsgJO9MP73fbApAyudf

**Analysis3**
"""

# Commented out IPython magic to ensure Python compatibility.
# imports
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 40)
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
# %matplotlib inline
sns.set_style('darkgrid')
import plotly.express as px
from sklearn.cluster import KMeans
import warnings
warnings.filterwarnings('ignore');

df = pd.read_csv("CARSSSS.csv")
# to display the top 5 rows
df.head(5)

df.tail(5)

"""Checking the type of data"""

df.dtypes

"""Dropping the duplicate rows"""

duplicate_rows_df = df[df.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

"""Now lets remove the duplicate data because its ok to remove them"""

df.count()   #used to count the number of rows

df = df.drop_duplicates()
df.head(5)

df.count()

print(df.isnull().sum())

df = df.dropna()    # Dropping the missing values.
df.count()

print(df.isnull().sum())   # After dropping the values

"""Now we check the relation power and price considering different body type"""

plt.figure(figsize=(20,10))
sns.scatterplot(data=df, x='Power', y='Price',hue='Make',palette='viridis',alpha=.89, s=120 );
plt.xticks(fontsize=20);
plt.yticks(fontsize=20)
plt.xlabel('power',fontsize=14)
plt.ylabel('price',fontsize=14)
plt.title('Relation between power and price',fontsize=20);

"""Heat Maps"""

# Plotting a heat map
plt.figure(figsize=(10,5))
c= df.corr()
sns.heatmap(c,cmap="BrBG",annot=True)

"""Heat Maps is a plot which is necessary when we need to find the dependent variables. One of the best ways to find the correlation between the features can be done using heat maps. As shown below the price feature (Price) has a strong correlation with power t,his is very important because the more the relationship between the variables the more accurate the model will be. This is how the correlation between the features can be found using heat maps. With the help of heat maps I can use these related features in building my model.

We can also look into the relation between Mileage and price
"""

fig = plt.figure(figsize= (30,10))

ax= fig.add_subplot()
sns.jointplot(data=df, x='City_Mileage', y='Price',ax=ax, palette='viridis',height=8,  ratio=7)

"""It's looks like expensive cars tend to have worse mileage

Now we check an extensive scatter plot grid of more numerical variable to investigate the realtion in more detail
"""

fig = px.scatter_3d(df, x='Power', z='Price', y='Variant',color='Make',width=800,height=750)
fig.update_layout(showlegend=True)
fig.show();